/** Master lists for spa stay fields. INSERT IGNORE so re-runs are safe. */

export const LANGUAGE_NAMES = [
  "English",
  "Hindi",
  "Malayalam",
  "Tamil",
  "Kannada",
  "Telugu",
  "Sanskrit",
  "Marathi",
  "Gujarati",
  "Bengali",
  "Punjabi",
  "Urdu",
  "Sinhala",
  "Nepali",
  "Indonesian",
  "Balinese",
  "German",
  "French",
  "Spanish",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Arabic",
  "Mandarin",
  "Japanese",
  "Korean",
  "Thai",
  "Vietnamese",
  "Swedish",
  "Norwegian",
  "Danish",
  "Polish",
  "Turkish",
  "Hebrew",
  "Persian",
];

export const DIETARY_NAMES = [
  "Vegetarian",
  "Vegan",
  "Sattvic",
  "Jain",
  "Gluten-free",
  "Dairy-free",
  "Lactose-free",
  "No onion or garlic",
  "Halal",
  "Kosher",
  "Organic",
  "Diabetic-friendly",
  "Vata-pacifying",
  "Pitta-pacifying",
  "Kapha-pacifying",
  "Low salt",
  "Nut-free",
  "Non-vegetarian",
];

export const ACCOMMODATION_NAMES = [
  "Standard room",
  "Deluxe room",
  "Suite",
  "Single occupancy",
  "Twin / double room",
  "Cottage",
  "Villa",
  "Heritage room",
  "Garden cottage",
  "Therapy cottage",
  "Dormitory",
  "Family cottage",
  "AC room",
  "Non-AC room",
  "River view room",
  "Mountain view room",
  "Shared room",
];
